config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/rails/letter_opener" if Rails.env.development?

  resources :cards
  resource :session
  resources :passwords, param: :token
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :card
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :title, :english_firstname, :english_lastname, :company_name, presence: true


  after_create_commit :send_email_notification

  def send_email_notification
    return unless user.is_a?(User)
    return unless user.email_address && user.notification_setting.email_card_notifications

    BadgeAchievements::SendEmailNotificationJob.perform_async(id)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/gdpr_delete_request.rb
class GdprDeleteRequest < ApplicationRecord
  validates :email, :user_id, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :card
end

app/models/notification.rb
class Notification < ApplicationRecord
  ALLOWED_POLYMORPIC_MODELS =  [ "Card" ].freeze
  private_constant :ALLOWED_POLYMORPIC_MODELS

  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  validates :user_id, uniqueness: { scope: [ :notifiable_id, :notifiable_type, :action ] }
  validates :notifiable_type, inclusion: { in: ALLOWED_POLYMORPIC_MODELS }

  before_create :mark_notified_at_time

  def send_new_badge_achievement_notification(badge_achievement)
    Notifications::NewBadgeAchievementJob.perform_async(badge_achievement.id)
  end

  private
  def mark_notified_at_time
    self.notified_at = Time.current
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource, polymorphic: true, optional: true
  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true

  scopify
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  HEX_COLOR_REGEX = /\A#(\h{6}|\h{3})\z/

  field :default_font, type: :string, default: "sans_serif"
  field :host, type: :string, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || "http://localhost:3000"), readonly: true
  field :default_locale, default: "en", type: :string

  field :primary_brand_color_hex, type: :string, default: "#3b49df", validates: {
    format: {
      with: HEX_COLOR_REGEX,
      message: proc { I18n.t("models.app_config.color_hex.message") }
    },
    color_contrast: true
  }
  field :accent_background_color_hex, type: :string, default: nil, validates: {
    format: {
      with: HEX_COLOR_REGEX,
      message: proc { I18n.t("models.app_config.color_hex.message") }
    },
    color_contrast: true
  }
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  rolify strict: true
  has_secure_password
  before_create :create_notification_settings_records

  has_one :notification_setting, class_name: "Users::NotificationSetting", dependent: :delete
  has_many :cards, dependent: :destroy
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def create_notification_settings_records
    self.notification_setting = Users::NotificationSetting.create
  end
end

app/models/users.rb
module Users
  def self.table_name_prefix
    "users_"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Pagy::Backend
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :determine_locale

  def determine_locale
    I18n.locale = if %w[en].include?(params[:locale])
      params[:locale]
    else
      Setting.default_locale
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Current.user.cards.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: "Card was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy!

    respond_to do |format|
      format.html { redirect_to cards_path, notice: "Card was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.expect(card: [ :english_firstname, :english_lastname, :chinese_name, :title, :chinese, :company_name, :company_address, :chinese_company_address ])
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= card.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">English firstname:</strong>
    <%= card.english_firstname %>
  </div>
  <div>
    <strong class="block font-medium mb-1">English lastname:</strong>
    <%= card.english_lastname %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Chinese name:</strong>
    <%= card.chinese_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Title:</strong>
    <%= card.title %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Chinese:</strong>
    <%= card.chinese %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Company name:</strong>
    <%= card.company_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Company address:</strong>
    <%= card.company_address %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Chinese company address:</strong>
    <%= card.chinese_company_address %>
  </div>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, class: "contents") do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul class="list-disc ml-6">
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :english_firstname %>
    <%= form.text_field :english_firstname, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:english_firstname].none?, "border-red-400 focus:outline-red-600": card.errors[:english_firstname].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :english_lastname %>
    <%= form.text_field :english_lastname, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:english_lastname].none?, "border-red-400 focus:outline-red-600": card.errors[:english_lastname].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :chinese_name %>
    <%= form.text_field :chinese_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:chinese_name].none?, "border-red-400 focus:outline-red-600": card.errors[:chinese_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:title].none?, "border-red-400 focus:outline-red-600": card.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :chinese %>
    <%= form.text_field :chinese, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:chinese].none?, "border-red-400 focus:outline-red-600": card.errors[:chinese].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:company_name].none?, "border-red-400 focus:outline-red-600": card.errors[:company_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :company_address %>
    <%= form.text_field :company_address, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:company_address].none?, "border-red-400 focus:outline-red-600": card.errors[:company_address].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :chinese_company_address %>
    <%= form.text_field :chinese_company_address, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:chinese_company_address].none?, "border-red-400 focus:outline-red-600": card.errors[:chinese_company_address].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<% content_for :title, "Editing card" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card</h1>

  <%= render "form", card: @card %>

  <%= link_to "Show this card", @card, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/cards/index.html.erb
<% content_for :title, "Cards" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cards</h1>
    <%= link_to "New card", new_card_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="cards" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @cards.any? %>
      <% @cards.each do |card| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render card %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", card, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_card_path(card), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", card, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No cards found.</p>
    <% end %>
  </div>
</div>

app/views/cards/new.html.erb
<% content_for :title, "New card" %>
<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New card</h1>
  <%= turbo_frame_tag "new_card" do %>
    <%= render "form", card: @card %>
  <% end %>
  <%= link_to "Back to cards", cards_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/cards/show.html.erb
<% content_for :title, "Showing card" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing card</h1>

  <%= render @card %>

  <%= link_to "Edit this card", edit_card_path(@card), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this card", @card, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>